### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by luwening** [ding-lab/CharGer#2]
python test_chargervariant.py 

E

======================================================================

ERROR: test_nonzero (__main__.testchargervariant)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "test_chargervariant.py", line 13, in test_nonzero

    if ( v ):

  File "/xxx/python2.7/site-packages/charger/chargervariant.py", line 201, in __nonzero__

    elif ( self.checkIfRefAltStrand( k ) ):

AttributeError: 'chargervariant' object has no attribute 'checkIfRefAltStrand'

----------------------------------------------------------------------

Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by amilacsw** [comment]
Hi @luwening,
Thanks for informing us about the error. This error is due to usage of outdated package in dependencies, Biomine. We updated the Biomine in Pypi to the most recent one (v0.9.5), which should fix the error you're encountering.

Please pull the latest version of charger and reinstall it using,
`cd path/to/CharGer`
`git pull`
 `pip install .`

Best,
Amila
